module.exports = {
  content: ["./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        nokia: ["Nokia", "sans-serif"],
        noto: ["Noto-Ethiopic", "sans"],
      },
    },
  },
  plugins: [],
  safelist: [
    "text-[8px]",
    "text-[10px]",
    "text-[12px]",
    "text-[14px]",
    "text-[16px]",
    "text-[20px]",
    "text-[24px]",
    "text-[28px]",
    "text-[30px]",
    "text-[32px]",
    "text-[36px]",
    "text-[48px]",
    "text-[50px]",
    "text-[56px]",
    "text-[60px]",
    "text-[64px]",
    "text-[72px]",
    "text-[96px]",
    "text-white",
    "text-left",
    "text-right",
    "text-center",
    "font-bold",
  ],
};
