import {
  app,
  BrowserWindow,
  ipcMain,
  dialog,
  screen,
  globalShortcut,
  Menu,
} from "electron";
import path from "path";
import { fileURLToPath } from "url";
import fs from "fs";
import { ExifParserFactory } from "ts-exif-parser";
import ffmpeg from "fluent-ffmpeg";
import * as cheerio from "cheerio";
import express from "express";
import os from "os";
import { convert } from "pdf-poppler";
import pkg from "electron-updater";

const { autoUpdater } = pkg;
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const server = express();

let projectorWindow = undefined;
let mainWindow = undefined;
let tutorialWindow = undefined;
let selectedIndex = 0;
let images = [];

server.use(express.json());
server.set("view engine", "ejs");
server.listen(3000, () => {
  console.log("Server is running on port 3000");
});

server.get("/remote", (_, res) => {
  res.render(
    app.isPackaged ? path.join(__dirname, "../views/remote") : "remote",
    {
      images,
      selectedIndex,
    }
  );
});

server.put("/remote", (req, res) => {
  const { index } = req.query;
  selectedIndex = index;

  projectorWindow.webContents.send("media-update", images[index]);
  mainWindow.webContents.send("source-index-update", Number.parseInt(index));

  res.sendStatus(200);
});

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
// declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
// declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
// Dynamically import electron-squirrel-startup for ESM compatibility
const checkSquirrel = async () => {
  const mod = await import("electron-squirrel-startup");
  if (mod.default) {
    app.quit();
  }
};
checkSquirrel();

const createWindow = () => {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    icon: "./public/logo-mini.png",
    webPreferences: {
      preload: path.join(__dirname, "preload.js"),
      contextIsolation: true,
    },
  });

  if (app.isPackaged) {
    mainWindow.loadFile(path.join(__dirname, "../dist/index.html"));
  } else {
    mainWindow.loadURL("http://localhost:5173");
  }

  mainWindow.maximize();
  autoUpdater.checkForUpdatesAndNotify();
  appendHelpMenuItems();

  mainWindow.on("close", (event) => {
    projectorWindow?.destroy();
    projectorWindow = undefined;
    mainWindow = undefined;
  });
};

const createProjectorWindow = () => {
  if (!projectorWindow) {
    const displays = screen.getAllDisplays();

    const externalDisplay = displays.find((display) => {
      return display.bounds.x !== 0 || display.bounds.y !== 0;
    });

    // Create the browser window.
    projectorWindow = new BrowserWindow({
      icon: "./public/logo-mini.png",
      frame: false,
      transparent: false,
      fullscreen: true,
      x: externalDisplay?.bounds.x ?? 0,
      y: externalDisplay?.bounds.y ?? 0,
      webPreferences: {
        preload: path.join(__dirname, "preload.js"),
        contextIsolation: true,
      },
    });

    if (app.isPackaged) {
      projectorWindow.loadFile(path.join(__dirname, "../dist/index.html"), {
        hash: "/projector",
      });
    } else {
      projectorWindow.loadURL("http://localhost:5173/projector");
    }

    // projectorWindow.webContents.toggleDevTools();
    projectorWindow.on("close", (event) => {
      projectorWindow = undefined;
    });
  }
};

const createTutorialWindow = () => {
  if (tutorialWindow) {
    tutorialWindow.focus();
    return;
  }
  // Create the browser window.
  tutorialWindow = new BrowserWindow({
    height: 600,
    width: 800,
    icon: "./public/logo-mini.png",
    webPreferences: {
      preload: path.join(__dirname, "preload.js"),
      contextIsolation: true,
    },
  });

  if (app.isPackaged) {
    tutorialWindow.loadFile(path.join(__dirname, "../dist/index.html"), {
      hash: "/tutorial",
    });
  } else {
    tutorialWindow.loadURL("http://localhost:5173/tutorial");
  }

  tutorialWindow.setMenu(null);
  tutorialWindow.setMaximizable(false);

  tutorialWindow.on("close", (event) => {
    tutorialWindow = undefined;
  });
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on("ready", () => {
  createWindow();

  globalShortcut.register("PageDown", () => {
    mainWindow.webContents.send("slide-update", "next");
  });

  globalShortcut.register("PageUp", () => {
    mainWindow.webContents.send("slide-update", "previous");
  });
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    const windows = BrowserWindow.getAllWindows();
    windows.forEach((win) => {
      win.destroy();
    });

    app.quit();
  }
});

app.on("activate", () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

autoUpdater.on("update-available", () => {
  //TODO: Show download progress
  dialog.showMessageBox({
    type: "info",
    title: "Update Available",
    message: "A new version is available. Downloading now...",
  });
});

autoUpdater.on("download-progress", (progressObj) => {
  const percent = Math.round(progressObj.percent);
  mainWindow.webContents.send("download_progress", percent);
});

autoUpdater.on("update-downloaded", () => {
  dialog
    .showMessageBox({
      type: "info",
      title: "Update Ready",
      message: "A new version has been downloaded. Restart now to install?",
      buttons: ["Restart", "Later"],
    })
    .then((result) => {
      if (result.response === 0) autoUpdater.quitAndInstall();
    });
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
ipcMain.handle("open-file-dialog", async () => {
  const result = await dialog.showOpenDialog({
    properties: ["openFile", "multiSelections"],
  });

  return result.filePaths;
});

ipcMain.handle("load-file", async (_, filePath) => {
  if (filePath.includes(".pdf")) {
    const folderPath = path.join(os.tmpdir(), "output");

    if (!fs.existsSync(folderPath)) {
      fs.mkdirSync(folderPath, { recursive: true });
    }

    const options = {
      format: "png",
      out_dir: folderPath,
      out_prefix: "page",
      page: null, // null = all pages
    };

    await convert(filePath, options);

    const imageFiles = fs
      .readdirSync(folderPath)
      .filter((f) => f.endsWith(".png"));

    const images = imageFiles.map((f) =>
      fs.readFileSync(path.join(folderPath, f)).toString("base64")
    );

    imageFiles.forEach((file) => fs.unlinkSync(path.join(folderPath, file)));

    return images;
  }

  const data = await fs.promises.readFile(filePath);

  return [data.toString("base64")];
});

ipcMain.handle("fetch-image-metadata", async (_, filePath) => {
  const buffer = fs.readFileSync(filePath);
  const parser = ExifParserFactory.create(buffer);
  const result = parser.parse();

  return result.imageSize;
});

ipcMain.handle("fetch-video-metadata", async (_event, filePath) => {
  return new Promise((resolve, reject) => {
    ffmpeg.ffprobe(filePath, (err, data) => {
      if (err) {
        reject(err);
      } else {
        resolve(data.format);
      }
    });
  });
});

ipcMain.on("media-update", (_, newSource, verse, styles, color) => {
  projectorWindow?.webContents.send(
    "media-update",
    newSource,
    verse,
    styles,
    color
  );
});

ipcMain.on("lyric-update", (_, newSource, verse, styles, color) => {
  projectorWindow?.webContents.send(
    "lyric-update",
    newSource,
    verse,
    styles,
    color
  );
});

ipcMain.on("open-projector-window", () => {
  createProjectorWindow();
});

ipcMain.on("close-projector-window", () => {
  projectorWindow?.destroy();
  projectorWindow = undefined;
  images = [];
  selectedIndex = 0;
});

ipcMain.on("video-control", (_event, { command, payload }) => {
  projectorWindow?.webContents.send("video-control", { command, payload });
});

ipcMain.handle("fetch-website", async (_, url, selector) => {
  try {
    const res = await fetch(url);
    const html = await res.text();

    const $ = cheerio.load(html);

    if (selector) {
      return $(selector)
        .map((i, el) => $(el).html())
        .get();
    }

    return html;
  } catch (error) {
    return null;
  }
});

ipcMain.handle("get-local-ip", () => {
  const nets = os.networkInterfaces();

  for (const name of Object.keys(nets)) {
    for (const net of nets[name]) {
      if (net.family === "IPv4" && !net.internal) {
        return net.address;
      }
    }
  }
});

ipcMain.handle("set-remote-images", (event, imgs) => {
  images = imgs;

  setTimeout(() => {
    projectorWindow.webContents.send("media-update", imgs[0]);
  }, 1000);
});

function appendHelpMenuItems() {
  // Get existing menu
  const existingMenu = Menu.getApplicationMenu();
  if (!existingMenu) return; // when no menu exists yet

  const template = existingMenu.items.map((item) => {
    return {
      label: item.label,
      submenu: item.submenu ? item.submenu.items : undefined,
    };
  });

  // Find help menu index
  const helpIndex = template.findIndex((item) => item.label === "Help");

  if (helpIndex !== -1) {
    // Append new submenu items
    template[helpIndex].submenu = [];
    template[helpIndex].submenu.push(
      {
        label: "Tutorial",
        click: () => {
          createTutorialWindow();
        },
      },
      {
        label: "Check for Updates",
        role: "",
        click: async () => {
          try {
            const result = await autoUpdater.checkForUpdatesAndNotify();

            if (result == null) return;

            if (!result.isUpdateAvailable) {
              dialog.showMessageBox({
                type: "info",
                title: "No Updates Available",
                message: "No updates are available.",
              });
            }
          } catch (error) {
            console.error(error);
          }
        },
      },
      {
        label: `Version (${app.getVersion()})`,
        enabled: false, // Makes it non-clickable
      }
    );
  }

  // Rebuild menu
  const newMenu = Menu.buildFromTemplate(template);
  Menu.setApplicationMenu(newMenu);
}
