name: Build Castor Installer

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: yarn install

      - name: Build Castor
        run: yarn run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: CastorInstaller
          path: dist/*.exe

      - name: Publish to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.exe